version: "3"
services:
  app:
    build: ./
    image: detect_test
    container_name: itri-bev-container
    volumes:
      - .:/docker
    working_dir: /docker
    environment:
      - DISPLAY=host.docker.internal:0.0
      - QT_DEBUG_PLUGINS=1
    